// <auto-generated />
using System;
using Group2Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group2Flight.Migrations
{
    [DbContext(typeof(Group2FlightDatabaseContext))]
    [Migration("20260405213047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Group2Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airline");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "emirates_airlines.png",
                            Name = "Emirates Airlines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "qatar_airways.png",
                            Name = "Qatar Airways"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "singapore_airlines.png",
                            Name = "Singapore Airlines"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "lufthansa.png",
                            Name = "Lufthansa"
                        },
                        new
                        {
                            AirlineId = 5,
                            ImageName = "air_france.png",
                            Name = "Air France"
                        },
                        new
                        {
                            AirlineId = 6,
                            ImageName = "british_airways.png",
                            Name = "British Airways"
                        });
                });

            modelBuilder.Entity("Group2Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Airbus A380",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 22, 15, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 2, 30, 0, 0),
                            Emission = 850.29999999999995,
                            FlightCode = "EK206",
                            From = "Dubai",
                            Price = 2500,
                            To = "Sydney"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Boeing 787 Dreamliner",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 13, 30, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 7, 45, 0, 0),
                            Emission = 320.80000000000001,
                            FlightCode = "QR123",
                            From = "Doha",
                            Price = 890,
                            To = "Paris"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus A350",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 17, 45, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 15, 0, 0),
                            Emission = 280.39999999999998,
                            FlightCode = "SQ345",
                            From = "Singapore",
                            Price = 680,
                            To = "Tokyo"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Airbus A340",
                            AirlineId = 4,
                            ArrivalTime = new TimeSpan(0, 1, 20, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 13, 50, 0, 0),
                            Emission = 410.5,
                            FlightCode = "LH456",
                            From = "Frankfurt",
                            Price = 540,
                            To = "Mumbai"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Boeing 777-300ER",
                            AirlineId = 5,
                            ArrivalTime = new TimeSpan(0, 6, 45, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 23, 15, 0, 0),
                            Emission = 620.70000000000005,
                            FlightCode = "AF789",
                            From = "Paris",
                            Price = 1350,
                            To = "Rio de Janeiro"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "Airbus A380",
                            AirlineId = 6,
                            ArrivalTime = new TimeSpan(0, 7, 15, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 18, 30, 0, 0),
                            Emission = 710.20000000000005,
                            FlightCode = "BA890",
                            From = "London",
                            Price = 980,
                            To = "Cape Town"
                        },
                        new
                        {
                            FlightId = 7,
                            AircraftType = "Boeing 777-200LR",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 10, 30, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 3, 45, 0, 0),
                            Emission = 780.5,
                            FlightCode = "EK567",
                            From = "Dubai",
                            Price = 2100,
                            To = "Miami"
                        },
                        new
                        {
                            FlightId = 8,
                            AircraftType = "Airbus A330",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 12, 45, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 1, 20, 0, 0),
                            Emission = 350.89999999999998,
                            FlightCode = "QR234",
                            From = "Doha",
                            Price = 470,
                            To = "Bangkok"
                        },
                        new
                        {
                            FlightId = 9,
                            AircraftType = "Airbus A350-900",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 8, 20, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 22, 40, 0, 0),
                            Emission = 490.19999999999999,
                            FlightCode = "SQ789",
                            From = "Singapore",
                            Price = 1120,
                            To = "Melbourne"
                        },
                        new
                        {
                            FlightId = 10,
                            AircraftType = "Boeing 747-8",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 15, 10, 0, 0),
                            Emission = 550.29999999999995,
                            FlightCode = "LH567",
                            From = "Munich",
                            Price = 780,
                            To = "Shanghai"
                        });
                });

            modelBuilder.Entity("Group2Flight.Models.FlightSelection", b =>
                {
                    b.Property<int>("FlightSelectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightSelectionId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightSelection");
                });

            modelBuilder.Entity("Group2Flight.Models.Flight", b =>
                {
                    b.HasOne("Group2Flight.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group2Flight.Models.FlightSelection", b =>
                {
                    b.HasOne("Group2Flight.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
